### ISSUE TITLE
Different formatting between android and desktop version

### ISSUE THREAD

**Issue by magnusdp** [SilasAlroe/OctoPub-Android#30]
The mobile android release and desktop web version displays text very differently, especially copypasta.
Pitchforks web on desktop:
![forks](https://cloud.githubusercontent.com/assets/26061035/23360611/98ffaee6-fcec-11e6-8215-6652b3d1a025.png)

Pitchforks android:
![android](https://cloud.githubusercontent.com/assets/26061035/23360593/82e6d346-fcec-11e6-8e2f-6ff30e9fd03a.jpg)

**Comment by magnusdp** [comment]
Which is very strange, considering the web version on mobile displays just fine:

![photo_2017-02-27_13-06-13](https://cloud.githubusercontent.com/assets/26061035/23360767/8a7bc6c4-fced-11e6-914a-e6b3aaad5b09.jpg)

**Comment by SilasAlroe** [comment]
This is a known issue, which has already been described in issue #19. As such this issue will be referenced in the original and closed. Thanks for the documenting pictures, though!
