### ISSUE TITLE
Suggestion: Make the Konami code do something

### ISSUE THREAD

**Issue by magnusdp** [SilasAlroe/OctoPub-Android#32]
A lot of cool sites have the konami code (up up, down down, left, right, left right, b, a, start) doing something, be it anything. It'd be a pretty rad addition, though not the most pressing issue.

**Comment by SilasAlroe** [comment]
How is one supposed to input the Konami code on an Android device?  
May I suggest that this is an issue for the [OctoPub](https://github.com/SilasAlroe/OctoPub) repo, not OctoPub-Android?
